name: finanza_personale
description: "Una app per la finanza personale scritta in Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  dio: ^5.5.0
  extended_image: ^8.2.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  package_info_plus: ^8.0.0
  riverpod_annotation: ^2.3.5
  universal_platform: ^1.1.0
  url_launcher: ^6.3.0
  window_manager: ^0.3.9

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: null
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  # Enable generation of localized values for supported locales from arb files
  generate: true
